language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
  - release
  - nightly
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - sudo apt-get install build-essential
  - sudo apt-get install gfortran
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("MomentBasedEstimators"); Pkg.test("MomentBasedEstimators"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("MomentBasedEstimators")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
